version: "1"
services:
  web:
    build: ./artform-web/
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: ./artform-web/content
        target: /code/content
      - user-content:/code/content/static/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: abcde123
    volumes:
      - db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db:
  user-content:
